$color = rgba(8, 13, 19, 1)
$inner_color = rgba(16, 24, 32, 0.86)
$outer_color = rgba(214, 168, 79, 1)
$font_color = rgba(240, 230, 200, 1)
$placeholder_color = rgba(198, 197, 180, 0.7)
$check_color = rgba(109, 143, 190, 1)
